import MaterialTable from 'material-table'
import Head from 'next/head'
import { useEffect, useState } from 'react';
import tableIcons from 'assets/icons/MaterialTableIcons';
import { useRouter } from 'next/dist/client/router';
import historyTransactionService from 'services/history-transaction.service';
import convertToRupiah from 'utils/convertToRupiah';
import { format } from 'date-fns';
import Modal from 'components/modal.component';
import { GetServerSidePropsContext } from 'next';



export async function getServerSideProps({ query }: GetServerSidePropsContext) {
    const { id } = query
    const response = await historyTransactionService.getHistoryTransaction(id)
    return {
        props: {
            externalPostData: response.data,
        }, // will be passed to the page component as props
    }
}

const HistoryTransaction: React.FC = (props) => {
    const { externalPostData }: any = props;
    const [data, setData]: any = useState([]);
    const [modal, setModal] = useState(true);
    const router = useRouter();

    useEffect(() => {
        const _data: object[] = [];
        (externalPostData || [])?.map((item: any) => {
            _data.push({
                id: item.id,
                transaction_id: item.transaction_id,
                member_id: item.member_id,
                amount: convertToRupiah(item?.transaction?.amount || 0),
                createdAt: item?.transaction?.createdAt ? format(new Date(item.transaction.createdAt), "dd MMM yyyy") : "-"
            })
        })
        setData(_data);
    }, [externalPostData])



    const dataColumn = [
        { title: "ID Transaksi", field: "transaction_id" },
        { title: "ID Member", field: "member_id" },
        { title: "amount", field: "amount" },
        { title: "Tanggal Transaksi", field: "createdAt" },
    ]

    const handlePress = (_, rowData: any) => {
        setModal(true)
    }

    return (
        <div className="container py-5">
            <Head>
                <title></title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MaterialTable
                columns={dataColumn}
                data={data}
                actions={[
                    {
                        icon: tableIcons.Search,
                        tooltip: 'Lihat Detail Transaksi',
                        onClick: handlePress,
                    }
                ]}
                title="List Transaksi"
            />
            <Modal.View modalIsOpen={modal} closeModal={() => setModal(false)}>
                <div>test</div>
            </Modal.View>
        </div>
    )
}

export default HistoryTransaction
