import MaterialTable from 'material-table'
import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react';
import memberService from 'services/member.service';
import { compareAsc, format } from 'date-fns'
import convertToRupiah from 'utils/convertToRupiah';
import tableIcons from 'assets/icons/MaterialTableIcons';
import { useRouter } from 'next/dist/client/router';

export const getStaticProps: GetStaticProps = async () => {
  const response = await memberService.getAllMembers()
  return {
    props: {
      externalPostData: response.data || [],
    },
  }
}

interface MemberProps {
  externalPostData: any;
}

const Member: React.FC<MemberProps> = (props: MemberProps) => {

  const { externalPostData } = props;
  const [data, setData]: any = useState([]);
  const router = useRouter()

  useEffect(() => {
    const _data: any = [];
    externalPostData.map((item: any) => _data.push({
      id: item.id,
      fullName: item.fullName,
      dateOfBirth: format(new Date(item.dateOfBirth), 'dd MMMM yyyy'),
      address: item.address,
      loanLimit: convertToRupiah(item.loanLimit)
    }))
    setData(_data)
  }, [externalPostData])

  const dataColumn = [
    { title: "Nama Lengkap", field: "fullName" },
    { title: "Tanggal Lahir", field: "dateOfBirth" },
    { title: "Alamat", field: "address" },
    { title: "Limit Pinjaman", field: "loanLimit" },
  ]

  const handleHistoryTransaction = (rowData: any) => {
    router.push({
      pathname: '/member/history-transaction',
      query: { id: rowData.id }
    })
  }

  return (
    <div className="container py-5">
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MaterialTable
        columns={dataColumn}
        data={data}
        actions={[
          {
            icon: tableIcons.Search,
            tooltip: 'Lihat History Transaksi',
            onClick: (_event, rowData) => handleHistoryTransaction(rowData),
          }
        ]}
        title="List Member"
      />
    </div>
  )
}

export default Member
