import { ICONS } from 'assets/icons'
import { IMAGES } from 'assets/images'
import type { NextPage } from 'next'
import { useRouter } from 'next/dist/client/router'
import Head from 'next/head'

const Home: NextPage = () => {
  const router = useRouter()

  const handleMemberArea = () => {
    router.push("/member")
  }
  return (
    <div className="container-fluid">

      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <img src={ICONS.HOME.BG_HOME} className="bgHome d-lg-flex d-none" />
      <div className="home-header">
        <div></div>
        <button onClick={() => handleMemberArea()}>Member Area</button>
      </div>
      <div className="content d-lg-flex d-block mx-5">

        <div className="leftContent col-12 col-md-6">
          <h1 className="my-5 fw-bold text-center text-lg-start">Koperasi Simpan Pinjam</h1>
          <h5 className="col-md-7 text-center text-lg-start">Koperasi simpan pinjam adalah lembaga yang bergerak dalam bidang keuangan dengan kegiatan usaha yang berupa menerima simpanan maupun pinjaman. ... Sumber pertama diperoleh dari simpanan anggota koperasi, baik yang bersifat simpanan pokok, simpanan wajib, simpanan sukarela atupun hibah.</h5>
        </div>
        <img src={IMAGES.HOME.VECTOR_COOPERATTION} className="vectorHome col-12 col-lg-6" />
      </div>
    </div>
  )
}

export default Home
